<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Alerts implements JsonSerializable
{
    /**
     * @var \WeatherAPILib\Models\Alert[]|null $alert public property
     */
    public $alert;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $alert  Initialization value for $this->alert
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->alert  = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['alert']  = $this->alert;

        return $json;
    }
}
