<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Alert implements JsonSerializable
{
    /**
     * @var string|null $alert public property
     */
    public $headline;

    /**
     * @var string|null $msgType public property
     */
    public $msgType;

    /**
     * @var string|null $severity public property
     */
    public $severity;

    /**
     * @var string|null $urgency public property
     */
    public $urgency;

    /**
     * @var string|null $areas public property
     */
    public $areas;

    /**
     * @var string|null $category public property
     */
    public $category;

    /**
     * @var string|null $certainty public property
     */
    public $certainty;

    /**
     * @var string|null $event public property
     */
    public $event;

    /**
     * @var string|null $note public property
     */
    public $note;

    /**
     * @var string|null $effective public property
     */
    public $effective;

    /**
     * @var string|null $expires public property
     */
    public $expires;

    /**
     * @var string|null $desc public property
     */
    public $desc;

    /**
     * @var string|null $ public property
     */
    public $instruction;

    /**
     * Constructor to set initial or default values of member properties
     * @param string|null $headline Initialization value for $this->headline
     * @param string|null $msgType Initialization value for $this->msgType
     * @param string|null $severity Initialization value for $this->severity
     * @param string|null $urgency Initialization value for $this->urgency
     * @param string|null $areas Initialization value for $this->areas
     * @param string|null $category Initialization value for $this->category
     * @param string|null $certainty Initialization value for $this->certainty
     * @param string|null $event Initialization value for $this->event
     * @param string|null $note Initialization value for $this->note
     * @param string|null $effective Initialization value for $this->effective
     * @param string|null $expires Initialization value for $this->expires
     * @param string|null $desc Initialization value for $this->desc
     * @param string|null $instruction Initialization value for $this->instruction
     */
    public function __construct()
    {
        if (13 == func_num_args()) {
            $this->headline = func_get_arg(0);
            $this->msgType = func_get_arg(1);
            $this->severity = func_get_arg(2);
            $this->urgency = func_get_arg(3);
            $this->areas = func_get_arg(4);
            $this->category = func_get_arg(5);
            $this->certainty = func_get_arg(6);
            $this->event = func_get_arg(7);
            $this->note = func_get_arg(8);
            $this->effective = func_get_arg(9);
            $this->expires = func_get_arg(10);
            $this->desc = func_get_arg(12);
            $this->instruction = func_get_arg(12);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['headline'] = $this->headline;
        $json['msgType'] = $this->msgType;
        $json['severity'] = $this->severity;
        $json['urgency'] = $this->urgency;
        $json['areas'] = $this->areas;
        $json['category'] = $this->category;
        $json['certainty'] = $this->certainty;
        $json['event'] = $this->event;
        $json['note'] = $this->note;
        $json['effective'] = $this->effective;
        $json['expires'] = $this->expires;
        $json['desc'] = $this->desc;
        $json['instruction'] = $this->instruction;

        return $json;
    }
}
