<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ForecastJsonResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Location|null $location public property
     */
    public $location;

    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Current|null $current public property
     */
    public $current;

    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Forecast|null $forecast public property
     */
    public $forecast;

    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Alerts $alerts public property
     */
    public $alerts;

    /**
     * Constructor to set initial or default values of member properties
     * @param Location $location Initialization value for $this->location
     * @param Current  $current  Initialization value for $this->current
     * @param Forecast $forecast Initialization value for $this->forecast
     * @param Alerts   $alerts Initialization value for $this->alerts
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->location = func_get_arg(0);
            $this->current  = func_get_arg(1);
            $this->forecast = func_get_arg(2);
            $this->alerts = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['location'] = $this->location;
        $json['current']  = $this->current;
        $json['forecast'] = $this->forecast;
        $json['alerts']   = $this->alerts;

        return $json;
    }
}
